#!/bin/sh
FILES=$(git diff --cached --name-only --diff-filter=ACMR | sed 's| |\\ |g')
[ -z "$FILES" ] && exit 0

# Prettify all selected files
echo "$FILES" | xargs ./node_modules/.bin/prettier --ignore-unknown --write

# Add back the modified/prettified files to staging
echo "$FILES" | xargs git add

exit 0

# !/bin/sh
# . "$(dirname "$0")/_/husky.sh"

# git-format-staged -f 'prettier --ignore-unknown --stdin --stdin-filepath "{}"' .
